#!/bin/bash
# Generate the final pdf

# Export images to include in latex documents

inkscape -z -f legend.svg -e legend.png -d 400
inkscape -z -f map.svg -e map.png -d 400

# Render latex pages

latexmk -pdf -pvc- -output-directory='output' front.tex
latexmk -c -output-directory='output' front.tex

latexmk -pdf -pvc- -output-directory='output' tables.tex
latexmk -c -output-directory='output' tables.tex

# Remove temporary bitmaps

rm legend.png
rm map.png

# Convert Inkscape pages to PDF

inkscape -z -f lmw.svg -A output/lmw.pdf --export-area-page
inkscape -z -f rmw.svg -A output/rmw.pdf --export-area-page

# Combine pages

cd output

pdfunite front.pdf rmw.pdf lmw.pdf tables.pdf 'Kangaroo Point Map'.pdf

rm front.pdf lmw.pdf rmw.pdf tables.pdf
